version: '3.8'

services:
  app:
    container_name: cadastrousuario
    restart: always
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3005:80"
